// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCozM0PzUTGLa6oDM2oJ8mi-LXbc83avKg',
    appId: '1:302892470008:android:80ee4f30a7f1f48453750d',
    messagingSenderId: '302892470008',
    projectId: 'mini-social-feed-app-48c46',
    storageBucket: 'mini-social-feed-app-48c46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi1UQlqvyNcDEnA2O3wN3vuQjwQZOj7KQ',
    appId: '1:302892470008:ios:97fe35d29c75c4df53750d',
    messagingSenderId: '302892470008',
    projectId: 'mini-social-feed-app-48c46',
    storageBucket: 'mini-social-feed-app-48c46.firebasestorage.app',
    iosClientId: '302892470008-382i8fp5n99lu57c193edd0tlgbndchh.apps.googleusercontent.com',
    iosBundleId: 'com.mnemdev.minisocialfeedapp',
  );
}
