name: my_fit_update
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_reactive_ble: ^5.4.0
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.0+1
  flutter_svg: ^2.1.0
  uuid: ^4.5.1

  cupertino_icons: ^1.0.8
  tab_container: ^3.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
