// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC481O-yTIiy_cb09Kwl0y2NxW7SZzsWQQ',
    appId: '1:576886383135:web:9c9bfa17a890ce1173ab2a',
    messagingSenderId: '576886383135',
    projectId: 'yallachat-4f063',
    authDomain: 'yallachat-4f063.firebaseapp.com',
    databaseURL: 'https://yallachat-4f063-default-rtdb.firebaseio.com',
    storageBucket: 'yallachat-4f063.appspot.com',
    measurementId: 'G-22WH3Y5Z84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJGReiT1YjYS0npMuRMV_ucDun-R2TvBU',
    appId: '1:576886383135:android:fcc0580ae0e17fd273ab2a',
    messagingSenderId: '576886383135',
    projectId: 'yallachat-4f063',
    databaseURL: 'https://yallachat-4f063-default-rtdb.firebaseio.com',
    storageBucket: 'yallachat-4f063.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtlq4KgtCclrXRglVDrDmyZtQcPcPbC5E',
    appId: '1:576886383135:ios:774ae771a6f9305573ab2a',
    messagingSenderId: '576886383135',
    projectId: 'yallachat-4f063',
    databaseURL: 'https://yallachat-4f063-default-rtdb.firebaseio.com',
    storageBucket: 'yallachat-4f063.appspot.com',
    iosBundleId: 'com.example.videoCallApp',
  );
}
