name: video_call_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  
  awesome_notifications: ^0.10.1
  firebase_core: ^3.13.1
  permission_handler: ^12.0.0+1
  agora_rtc_engine: ^6.5.2
  firebase_messaging: ^15.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^5.0.0
flutter:  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
